"""empty message

Revision ID: 225d26879455
Revises: b673c38768cd
Create Date: 2023-06-01 12:53:50.598753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225d26879455'
down_revision = 'b673c38768cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('game_result')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_result', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
