"""empty message

Revision ID: 3a014a4446a8
Revises: d0df1574bbd1
Create Date: 2023-05-16 11:24:53.208212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a014a4446a8'
down_revision = 'd0df1574bbd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=300), nullable=True))

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=50), server_default='scheduled', nullable=False))
        batch_op.alter_column('game_result',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('guardian', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=300), nullable=True))

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=300), nullable=True))

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('guardian', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.alter_column('game_result',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('status')
        batch_op.drop_column('location')

    with op.batch_alter_table('coach', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
