"""empty message

Revision ID: 9c8995e2f374
Revises: f02a88fc27b4
Create Date: 2023-05-16 11:28:57.294609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c8995e2f374'
down_revision = 'f02a88fc27b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=300), nullable=True))
        batch_op.drop_column('imaimage_urlge')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imaimage_urlge', sa.VARCHAR(length=300), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
