"""empty message

Revision ID: b673c38768cd
Revises: 511917c4be4f
Create Date: 2023-05-31 12:33:50.575511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b673c38768cd'
down_revision = '511917c4be4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('team_id', sa.INTEGER(), nullable=False),
    sa.Column('author_coach_id', sa.INTEGER(), nullable=True),
    sa.Column('author_parent_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['author_coach_id'], ['coach.id'], ),
    sa.ForeignKeyConstraint(['author_parent_id'], ['parent.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
