"""empty message

Revision ID: f02a88fc27b4
Revises: 3a014a4446a8
Create Date: 2023-05-16 11:28:05.050528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f02a88fc27b4'
down_revision = '3a014a4446a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=300), nullable=True))
        batch_op.drop_column('image')

    with op.batch_alter_table('guardian', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=300), nullable=True))
        batch_op.drop_column('image')

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imaimage_urlge', sa.String(length=300), nullable=True))
        batch_op.drop_column('image')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=300), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=300), nullable=True))
        batch_op.drop_column('image_url')

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=300), nullable=True))
        batch_op.drop_column('imaimage_urlge')

    with op.batch_alter_table('guardian', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=300), nullable=True))
        batch_op.drop_column('image_url')

    with op.batch_alter_table('coach', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=300), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
